# Generated by Django 3.2.25 on 2025-07-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogProxy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('html_code', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('publish', 'Published')], max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'admin_panel_blog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseBasicInfoProxy',
            fields=[
                ('_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='course_name', max_length=255)),
                ('course_code', models.CharField(max_length=50, unique=True)),
                ('year', models.IntegerField()),
                ('branch', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('group', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'admin_panel_coursebasicinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'admin_panel_notification',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='appuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
