# Generated by Django 3.1.12 on 2024-12-21 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0002_appuser_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProxy',
            fields=[
                ('_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('university', models.CharField(max_length=255)),
                ('file_input', djongo.models.fields.JSONField(default=list)),
                ('vectorized_data', djongo.models.fields.JSONField(default=dict)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'admin_panel_course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreferredSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_users', to='mobile_api.courseproxy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
    ]
