# Generated by Django 3.1.12 on 2024-12-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0006_chathistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chathistory',
            old_name='query',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='chathistory',
            old_name='response',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='chathistory',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='course',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='input_tokens',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='output_tokens',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='course_code',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
